-- -----------------------------------------------------
-- Remove test data
-- -----------------------------------------------------
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE expense;
TRUNCATE TABLE account;
TRUNCATE TABLE category;
TRUNCATE TABLE authority;
TRUNCATE TABLE user;
TRUNCATE TABLE exchange_rate;
TRUNCATE TABLE currency;
SET FOREIGN_KEY_CHECKS=1;
TRUNCATE TABLE mcc;

-- -----------------------------------------------------
-- Insert currency data
-- -----------------------------------------------------
INSERT INTO currency (name, code, symbol) VALUES
    ('Leke', 'ALL', 'Lek'),
    ('Dollars', 'USD', '$'),
    ('Afghanis', 'AFN', '؋'),
    ('Pesos', 'ARS', '$'),
    ('Guilders', 'AWG', 'ƒ'),
    ('Dollars', 'AUD', '$'),
    ('New Manats', 'AZN', 'ман'),
    ('Dollars', 'BSD', '$'),
    ('Dollars', 'BBD', '$'),
    ('Rubles', 'BYR', 'p.'),
    ('Euro', 'EUR', '€'),
    ('Dollars', 'BZD', 'BZ$'),
    ('Dollars', 'BMD', '$'),
    ('Bolivianos', 'BOB', '$b'),
    ('Convertible Marka', 'BAM', 'KM'),
    ('Pula', 'BWP', 'P'),
    ('Leva', 'BGN', 'лв'),
    ('Reais', 'BRL', 'R$'),
    ('Pounds', 'GBP', '£'),
    ('Dollars', 'BND', '$'),
    ('Riels', 'KHR', '៛'),
    ('Dollars', 'CAD', '$'),
    ('Dollars', 'KYD', '$'),
    ('Pesos', 'CLP', '$'),
    ('Yuan Renminbi', 'CNY', '¥'),
    ('Pesos', 'COP', '$'),
    ('Colón', 'CRC', '₡'),
    ('Kuna', 'HRK', 'kn'),
    ('Pesos', 'CUP', '₱'),
    ('Koruny', 'CZK', 'Kč'),
    ('Kroner', 'DKK', 'kr'),
    ('Pesos', 'DOP ', 'RD$'),
    ('Dollars', 'XCD', '$'),
    ('Pounds', 'EGP', '£'),
    ('Colones', 'SVC', '$'),
    ('Pounds', 'FKP', '£'),
    ('Dollars', 'FJD', '$'),
    ('Cedis', 'GHC', '¢'),
    ('Pounds', 'GIP', '£'),
    ('Quetzales', 'GTQ', 'Q'),
    ('Pounds', 'GGP', '£'),
    ('Dollars', 'GYD', '$'),
    ('Lempiras', 'HNL', 'L'),
    ('Dollars', 'HKD', '$'),
    ('Forint', 'HUF', 'Ft'),
    ('Kronur', 'ISK', 'kr'),
    ('Rupees', 'INR', 'Rp'),
    ('Rupiahs', 'IDR', 'Rp'),
    ('Rials', 'IRR', '﷼'),
    ('Pounds', 'IMP', '£'),
    ('New Shekels', 'ILS', '₪'),
    ('Dollars', 'JMD', 'J$'),
    ('Yen', 'JPY', '¥'),
    ('Pounds', 'JEP', '£'),
    ('Tenge', 'KZT', 'лв'),
    ('Won', 'KPW', '₩'),
    ('Won', 'KRW', '₩'),
    ('Soms', 'KGS', 'лв'),
    ('Kips', 'LAK', '₭'),
    ('Lati', 'LVL', 'Ls'),
    ('Pounds', 'LBP', '£'),
    ('Dollars', 'LRD', '$'),
    ('Switzerland Francs', 'CHF', 'CHF'),
    ('Litai', 'LTL', 'Lt'),
    ('Denars', 'MKD', 'ден'),
    ('Ringgits', 'MYR', 'RM'),
    ('Rupees', 'MUR', '₨'),
    ('Pesos', 'MXN', '$'),
    ('Tugriks', 'MNT', '₮'),
    ('Meticais', 'MZN', 'MT'),
    ('Dollars', 'NAD', '$'),
    ('Rupees', 'NPR', '₨'),
    ('Guilders', 'ANG', 'ƒ'),
    ('Dollars', 'NZD', '$'),
    ('Cordobas', 'NIO', 'C$'),
    ('Nairas', 'NGN', '₦'),
    ('Krone', 'NOK', 'kr'),
    ('Rials', 'OMR', '﷼'),
    ('Rupees', 'PKR', '₨'),
    ('Balboa', 'PAB', 'B/.'),
    ('Guarani', 'PYG', 'Gs'),
    ('Nuevos Soles', 'PEN', 'S/.'),
    ('Pesos', 'PHP', 'Php'),
    ('Zlotych', 'PLN', 'zł'),
    ('Rials', 'QAR', '﷼'),
    ('New Lei', 'RON', 'lei'),
    ('Rubles', 'RUB', 'руб'),
    ('Pounds', 'SHP', '£'),
    ('Riyals', 'SAR', '﷼'),
    ('Dinars', 'RSD', 'Дин.'),
    ('Rupees', 'SCR', '₨'),
    ('Dollars', 'SGD', '$'),
    ('Dollars', 'SBD', '$'),
    ('Shillings', 'SOS', 'S'),
    ('Rand', 'ZAR', 'R'),
    ('Rupees', 'LKR', '₨'),
    ('Kronor', 'SEK', 'kr'),
    ('Dollars', 'SRD', '$'),
    ('Pounds', 'SYP', '£'),
    ('New Dollars', 'TWD', 'NT$'),
    ('Baht', 'THB', '฿'),
    ('Dollars', 'TTD', 'TT$'),
    ('Lira', 'TRY', 'TL'),
    ('Liras', 'TRL', '£'),
    ('Dollars', 'TVD', '$'),
    ('Hryvnia', 'UAH', '₴'),
    ('Pesos', 'UYU', '$U'),
    ('Sums', 'UZS', 'лв'),
    ('Bolivares Fuertes', 'VEF', 'Bs'),
    ('Dong', 'VND', '₫'),
    ('Rials', 'YER', '﷼'),
    ('Zimbabwe Dollars', 'ZWD', 'Z$');

-- -----------------------------------------------------
-- Add iban currency codes to `currency` table
-- -----------------------------------------------------
UPDATE currency SET number=8   WHERE code = 'ALL';
UPDATE currency SET number=840 WHERE code = 'USD';
UPDATE currency SET number=971 WHERE code = 'AFN';
UPDATE currency SET number=32  WHERE code = 'ARS';
UPDATE currency SET number=533 WHERE code = 'AWG';
UPDATE currency SET number=36  WHERE code = 'AUD';
UPDATE currency SET number=944 WHERE code = 'AZN';
UPDATE currency SET number=44  WHERE code = 'BSD';
UPDATE currency SET number=52  WHERE code = 'BBD';
UPDATE currency SET number=933 WHERE code = 'BYR';
UPDATE currency SET number=978 WHERE code = 'EUR';
UPDATE currency SET number=84  WHERE code = 'BZD';
UPDATE currency SET number=60  WHERE code = 'BMD';
UPDATE currency SET number=68  WHERE code = 'BOB';
UPDATE currency SET number=977 WHERE code = 'BAM';
UPDATE currency SET number=72  WHERE code = 'BWP';
UPDATE currency SET number=975 WHERE code = 'BGN';
UPDATE currency SET number=986 WHERE code = 'BRL';
UPDATE currency SET number=826 WHERE code = 'GBP';
UPDATE currency SET number=96  WHERE code = 'BND';
UPDATE currency SET number=116 WHERE code = 'KHR';
UPDATE currency SET number=124 WHERE code = 'CAD';
UPDATE currency SET number=136 WHERE code = 'KYD';
UPDATE currency SET number=152 WHERE code = 'CLP';
UPDATE currency SET number=156 WHERE code = 'CNY';
UPDATE currency SET number=170 WHERE code = 'COP';
UPDATE currency SET number=188 WHERE code = 'CRC';
UPDATE currency SET number=191 WHERE code = 'HRK';
UPDATE currency SET number=192 WHERE code = 'CUP';
UPDATE currency SET number=203 WHERE code = 'CZK';
UPDATE currency SET number=208 WHERE code = 'DKK';
UPDATE currency SET number=214 WHERE code = 'DOP';
UPDATE currency SET number=951 WHERE code = 'XCD';
UPDATE currency SET number=818 WHERE code = 'EGP';
UPDATE currency SET number=222 WHERE code = 'SVC';
UPDATE currency SET number=238 WHERE code = 'FKP';
UPDATE currency SET number=242 WHERE code = 'FJD';
UPDATE currency SET number=936 WHERE code = 'GHC';
UPDATE currency SET number=292 WHERE code = 'GIP';
UPDATE currency SET number=320 WHERE code = 'GTQ';
UPDATE currency SET number=328 WHERE code = 'GYD';
UPDATE currency SET number=340 WHERE code = 'HNL';
UPDATE currency SET number=344 WHERE code = 'HKD';
UPDATE currency SET number=348 WHERE code = 'HUF';
UPDATE currency SET number=352 WHERE code = 'ISK';
UPDATE currency SET number=356 WHERE code = 'INR';
UPDATE currency SET number=360 WHERE code = 'IDR';
UPDATE currency SET number=364 WHERE code = 'IRR';
UPDATE currency SET number=376 WHERE code = 'ILS';
UPDATE currency SET number=388 WHERE code = 'JMD';
UPDATE currency SET number=392 WHERE code = 'JPY';
UPDATE currency SET number=398 WHERE code = 'KZT';
UPDATE currency SET number=408 WHERE code = 'KPW';
UPDATE currency SET number=410 WHERE code = 'KRW';
UPDATE currency SET number=417 WHERE code = 'KGS';
UPDATE currency SET number=418 WHERE code = 'LAK';
UPDATE currency SET number=422 WHERE code = 'LBP';
UPDATE currency SET number=430 WHERE code = 'LRD';
UPDATE currency SET number=756 WHERE code = 'CHF';
UPDATE currency SET number=807 WHERE code = 'MKD';
UPDATE currency SET number=458 WHERE code = 'MYR';
UPDATE currency SET number=480 WHERE code = 'MUR';
UPDATE currency SET number=484 WHERE code = 'MXN';
UPDATE currency SET number=496 WHERE code = 'MNT';
UPDATE currency SET number=943 WHERE code = 'MZN';
UPDATE currency SET number=516 WHERE code = 'NAD';
UPDATE currency SET number=524 WHERE code = 'NPR';
UPDATE currency SET number=532 WHERE code = 'ANG';
UPDATE currency SET number=554 WHERE code = 'NZD';
UPDATE currency SET number=558 WHERE code = 'NIO';
UPDATE currency SET number=566 WHERE code = 'NGN';
UPDATE currency SET number=578 WHERE code = 'NOK';
UPDATE currency SET number=512 WHERE code = 'OMR';
UPDATE currency SET number=586 WHERE code = 'PKR';
UPDATE currency SET number=590 WHERE code = 'PAB';
UPDATE currency SET number=600 WHERE code = 'PYG';
UPDATE currency SET number=604 WHERE code = 'PEN';
UPDATE currency SET number=608 WHERE code = 'PHP';
UPDATE currency SET number=985 WHERE code = 'PLN';
UPDATE currency SET number=634 WHERE code = 'QAR';
UPDATE currency SET number=946 WHERE code = 'RON';
UPDATE currency SET number=643 WHERE code = 'RUB';
UPDATE currency SET number=654 WHERE code = 'SHP';
UPDATE currency SET number=682 WHERE code = 'SAR';
UPDATE currency SET number=941 WHERE code = 'RSD';
UPDATE currency SET number=690 WHERE code = 'SCR';
UPDATE currency SET number=702 WHERE code = 'SGD';
UPDATE currency SET number=90  WHERE code = 'SBD';
UPDATE currency SET number=706 WHERE code = 'SOS';
UPDATE currency SET number=710 WHERE code = 'ZAR';
UPDATE currency SET number=144 WHERE code = 'LKR';
UPDATE currency SET number=752 WHERE code = 'SEK';
UPDATE currency SET number=968 WHERE code = 'SRD';
UPDATE currency SET number=760 WHERE code = 'SYP';
UPDATE currency SET number=901 WHERE code = 'TWD';
UPDATE currency SET number=764 WHERE code = 'THB';
UPDATE currency SET number=780 WHERE code = 'TTD';
UPDATE currency SET number=949 WHERE code = 'TRY';
UPDATE currency SET number=980 WHERE code = 'UAH';
UPDATE currency SET number=858 WHERE code = 'UYU';
UPDATE currency SET number=860 WHERE code = 'UZS';
UPDATE currency SET number=937 WHERE code = 'VEF';
UPDATE currency SET number=704 WHERE code = 'VND';
UPDATE currency SET number=886 WHERE code = 'YER';

-- -----------------------------------------------------
-- Insert exchange rate data
-- -----------------------------------------------------
INSERT INTO exchange_rate (base_currency, target_currency, rate, exchange_date) VALUES
    ('UAH', 'USD', 27.933, '2021-03-03'),
    ('UAH', 'EUR', 33.6006, '2021-03-03'),
    ('UAH', 'GBP', 38.8674, '2021-03-03');

-- -----------------------------------------------------
-- Insert mcc data
-- -----------------------------------------------------
INSERT INTO mcc (mcc_id, description, category_name) VALUES
    (742,'Ветеринарные услуги','Animals'),
    (763,'Сельскохозяйственные кооперативы','Other'),
    (780,'Услуги садоводства и ландшафтного дизайна','Repair'),
    (1520,'Генеральные подрядчики – жилое и коммерческое строительство','Repair'),
    (1711,'Генеральные подрядчики по вентиляции, теплоснабжению и водопроводу','Repair'),
    (1731,'Подрядчики по электричеству','Repair'),
    (1740,'Изоляция, мозаика, штукатурные работы, каменная кладка, облицовка плиткой, кафелем','Repair'),
    (1750,'Столярные работы','Repair'),
    (1761,'Кровельные и сайдинговые работы, обработка листового металла','Repair'),
    (1771,'Подрядчики бетонных работ','Repair'),
    (1799,'Контрактные услуги – нигде более не классифицированные','Other'),
    (2741,'Различные издательства/ печатное дело','Other'),
    (2791,'Набор текстов, шрифтов, таблиц и относящиеся к этому услуги','Other'),
    (2842,'Специальная обработка, полировка, санитария','Other'),
    (3000,'United Airlines (UNITED)','Travel'),
    (3001,'American Airlines (AMERICAN)','Travel'),
    (3002,'Pan American (PAN AM)','Travel'),
    (3003,'Eurofly (EUROFLY)','Travel'),
    (3004,'Dragonair (DRAGONAIR)','Travel'),
    (3005,'British Airways (BRITISH A)','Travel'),
    (3006,'Japan Air Lines (JAL)','Travel'),
    (3007,'Air France (AIR FRAN)','Travel'),
    (3008,'Lufthansa (LUFTHAN)','Travel'),
    (3009,'Air Canada (AIR CAN)','Travel'),
    (3010,'Royal Dutch Airlines (KLM)','Travel'),
    (3011,'Aeroflot (AEROFLOT)','Travel'),
    (3012,'Qantas (QANTAS)','Travel'),
    (3013,'Alitalia (ALITALIA)','Travel'),
    (3014,'Saudi Arabian Airlines (SAUDI AI)','Travel'),
    (3015,'Swiss International Air Lines (SWISS)','Travel'),
    (3016,'Scandinavian Airline System (SAS)','Travel'),
    (3017,'South African Airways (SAFRICAN)','Travel'),
    (3018,'Varig (Brazil) (VARIG)','Travel'),
    (3019,'Авиалинии, авиакомпании','Travel'),
    (3020,'Air India (AIR-INDI)','Travel'),
    (3021,'Air Algerie (AIRALGER)','Travel'),
    (3022,'Philippine Airlines (PAL AIR)','Travel'),
    (3023,'Mexicana (MEXICANA)','Travel'),
    (3024,'Pakistan International (PAKISTAN)','Travel'),
    (3025,'Air New Zealand Limited International (AIR NZ)','Travel'),
    (3026,'Emirates Airlines (EMIRATES)','Travel'),
    (3027,'Union de Transports Aeriens (UTAAIR)','Travel'),
    (3028,'Air Malta (AIRMALTA)','Travel'),
    (3029,'SN Brussels Airlines (SNBRU AIR)','Travel'),
    (3030,'Aerolineas Argentinas (AERO ARG)','Travel'),
    (3031,'Olympic Airways (OLYMPICA)','Travel'),
    (3032,'El Al (EL AL)','Travel'),
    (3033,'Ansett Airlines (ANSETT)','Travel'),
    (3034,'Etihad Airways (ETIHADAIR)','Travel'),
    (3035,'Tap (Portugal) (TAP)','Travel'),
    (3036,'VASP (Brazil) (VASP)','Travel'),
    (3037,'EgyptAir (EGYPTAIR)','Travel'),
    (3038,'Kuwait Airways (KUWAIT)','Travel'),
    (3039,'Avianca (AVIANCA)','Travel'),
    (3040,'Gulf Air (Bahrain) (GULF AIR)','Travel'),
    (3041,'Balkan—Bulgarian Airlines (BALKAN)','Travel'),
    (3042,'Finnair (FINNAIR)','Travel'),
    (3043,'Aer Lingus (AERLING)','Travel'),
    (3044,'Air Lanka (AIR LANKA)','Travel'),
    (3045,'Nigeria Airways (NIGERIA)','Travel'),
    (3046,'Cruzeiro do Sul (Brazil) (CRUZEIRO)','Travel'),
    (3047,'THY (Turkey) (THY)','Travel'),
    (3048,'Royal Air Maroc (AIRMARO)','Travel'),
    (3049,'Tunis Air (TUNIS AI)','Travel'),
    (3050,'Icelandair (ICELANDA)','Travel'),
    (3051,'Austrian Airlines (AUSTRIAN)','Travel'),
    (3052,'LAN Airlines (LAN AIR)','Travel'),
    (3053,'AVIACO (Spain) (AVIACO)','Travel'),
    (3054,'LADECO (Chile) (LADECO)','Travel'),
    (3055,'LAB (Bolivia) (LAB)','Travel'),
    (3056,'Jet Airways (JET AIR)','Travel'),
    (3057,'Virgin America (VIR AMER)','Travel'),
    (3058,'Delta (DELTA)','Travel'),
    (3059,'DBA Airlines (DBA AIR)','Travel'),
    (3060,'Northwest Airlines (NWA AIR)','Travel'),
    (3061,'Continental (CONTINEN)','Travel'),
    (3062,'Hapag-Lloyd Express (HLX)','Travel'),
    (3063,'U.S. Airways (USAIRWYS)','Travel'),
    (3064,'Adria Airways (ADRIA AIR)','Travel'),
    (3065,'Air Inter (AIRINTER)','Travel'),
    (3066,'Southwest Airlines (SOUTHWES)','Travel'),
    (3067,'Vanguard Airlines (VANGUARD)','Travel'),
    (3068,'Air Astana (AIRSTANA)','Travel'),
    (3069,'Sun Country Airlines (SUNCNTRY)','Travel'),
    (3071,'Air British Columbia (AIR B R C)','Travel'),
    (3072,'Cebu Pacific (CEBU PAC)','Travel'),
    (3073,'Air Cal','Travel'),
    (3075,'Singapore Airlines (SINGAPOR)','Travel'),
    (3076,'Aeromexico (AEROMEXI)','Travel'),
    (3077,'Thai Airways (THAIAIRW)','Travel'),
    (3078,'China Airlines (CHINAAIR)','Travel'),
    (3079,'Jetstar Airways (JETSTAR)','Travel'),
    (3081,'Авиалинии, авиакомпании','Travel'),
    (3082,'Korean Airlines (KOREAN)','Travel'),
    (3083,'Air Afrique (AIR AFRIQ)','Travel'),
    (3084,'Eva Airways (EVA AIR)','Travel'),
    (3085,'Midwest Express Airlines (MIDWEST)','Travel'),
    (3086,'Carnival Airlines','Travel'),
    (3087,'Metro Airlines (METROAI)','Travel'),
    (3088,'Croatia Air (CROATIA)','Travel'),
    (3089,'Transaero (TRANSAERO)','Travel'),
    (3090,'Uni Airways (UNIAIR)','Travel'),
    (3092,'Midway Airlines','Travel'),
    (3093,'Авиалинии, авиакомпании','Travel'),
    (3094,'Zambia Airways (ZAMBIA A)','Travel'),
    (3095,'Авиалинии, авиакомпании','Travel'),
    (3096,'Air Zimbabwe (AIRZIMBA)','Travel'),
    (3097,'Spanair (SPANAIR)','Travel'),
    (3098,'Asiana Airlines (ASIANA)','Travel'),
    (3099,'Cathay Pacific (CATHAYPA)','Travel'),
    (3100,'Malaysian Airline System (MALAY AI)','Travel'),
    (3101,'Авиалинии, авиакомпании','Travel'),
    (3102,'Iberia (IBERIA)','Travel'),
    (3103,'Garuda (Indonesia) (GARUDA)','Travel'),
    (3104,'Авиалинии, авиакомпании','Travel'),
    (3105,'Авиалинии, авиакомпании','Travel'),
    (3106,'Braathens S.A.F.E. (Norway) (BRAATHEN)','Travel'),
    (3107,'Авиалинии, авиакомпании','Travel'),
    (3109,'Авиалинии, авиакомпании','Travel'),
    (3110,'Авиалинии, авиакомпании','Travel'),
    (3111,'British Midland (BRITISH M)','Travel'),
    (3112,'Windward Island (WINDWARD)','Travel'),
    (3113,'Авиалинии, авиакомпании','Travel'),
    (3114,'Авиалинии, авиакомпании','Travel'),
    (3115,'Авиалинии, авиакомпании','Travel'),
    (3116,'Авиалинии, авиакомпании','Travel'),
    (3117,'Venezolana International de Aviacion (VIASA)','Travel'),
    (3118,'Авиалинии, авиакомпании','Travel'),
    (3119,'Авиалинии, авиакомпании','Travel'),
    (3120,'Авиалинии, авиакомпании','Travel'),
    (3121,'Авиалинии, авиакомпании','Travel'),
    (3122,'Авиалинии, авиакомпании','Travel'),
    (3123,'Авиалинии, авиакомпании','Travel'),
    (3124,'Авиалинии, авиакомпании','Travel'),
    (3125,'Tan Airlines (TAN AIR)','Travel'),
    (3126,'Авиалинии, авиакомпании','Travel'),
    (3127,'Taca International (TACA INT)','Travel'),
    (3128,'Авиалинии, авиакомпании','Travel'),
    (3129,'Surinam Airways (SURINAM)','Travel'),
    (3130,'Sunworld International Airways (SUNWORLD)','Travel'),
    (3131,'VLM Airlines (VLM)','Travel'),
    (3132,'Frontier Airlines (FRONTIER)','Travel'),
    (3133,'Авиалинии, авиакомпании','Travel'),
    (3134,'Авиалинии, авиакомпании','Travel'),
    (3135,'Авиалинии, авиакомпании','Travel'),
    (3136,'Qatar Airways Company W.L.L. (QATAR AIR)','Travel'),
    (3137,'Авиалинии, авиакомпании','Travel'),
    (3138,'Авиалинии, авиакомпании','Travel'),
    (3139,'Авиалинии, авиакомпании','Travel'),
    (3140,'Авиалинии, авиакомпании','Travel'),
    (3141,'Авиалинии, авиакомпании','Travel'),
    (3142,'Авиалинии, авиакомпании','Travel'),
    (3143,'Авиалинии, авиакомпании','Travel'),
    (3144,'Virgin Atlantic (VIR ATL)','Travel'),
    (3145,'Авиалинии, авиакомпании','Travel'),
    (3146,'Luxair (LUXAIR)','Travel'),
    (3147,'Авиалинии, авиакомпании','Travel'),
    (3148,'Air Littoral, S.A. (LITTORAL)','Travel'),
    (3150,'Авиалинии, авиакомпании','Travel'),
    (3151,'Air Zaire (AIRZAIRE)','Travel'),
    (3152,'Авиалинии, авиакомпании','Travel'),
    (3153,'Авиалинии, авиакомпании','Travel'),
    (3154,'Авиалинии, авиакомпании','Travel'),
    (3155,'Авиалинии, авиакомпании','Travel'),
    (3156,'GO FLY Ltd. (GOFLY)','Travel'),
    (3157,'Авиалинии, авиакомпании','Travel'),
    (3158,'Авиалинии, авиакомпании','Travel'),
    (3159,'Provincetown-Boston Airways (PBA)','Travel'),
    (3160,'Авиалинии, авиакомпании','Travel'),
    (3161,'All Nippon Airways (ANAAIR)','Travel'),
    (3162,'Авиалинии, авиакомпании','Travel'),
    (3163,'Авиалинии, авиакомпании','Travel'),
    (3164,'Norontair (NORONTAI)','Travel'),
    (3165,'Авиалинии, авиакомпании','Travel'),
    (3166,'Авиалинии, авиакомпании','Travel'),
    (3167,'Aero Continente (AERO CONT)','Travel'),
    (3168,'Авиалинии, авиакомпании','Travel'),
    (3169,'Авиалинии, авиакомпании','Travel'),
    (3170,'Авиалинии, авиакомпании','Travel'),
    (3171,'Canadian Airlines (CANADIAN)','Travel'),
    (3172,'Nation Air (NATIONAI)','Travel'),
    (3173,'Авиалинии, авиакомпании','Travel'),
    (3174,'JetBlue Airways (JETBLUE)','Travel'),
    (3175,'Middle East Air (MIDEASTA)','Travel'),
    (3176,'Авиалинии, авиакомпании','Travel'),
    (3177,'AirTran Airways (AIRTRAN A)','Travel'),
    (3178,'Mesa Air (MESA AIR)','Travel'),
    (3179,'Авиалинии, авиакомпании','Travel'),
    (3180,'Westjet Airlines (WESTJET)','Travel'),
    (3181,'Malev Hungarian Airlines (MALEV)','Travel'),
    (3182,'LOT – Polish Airlines (LOT)','Travel'),
    (3183,'Oman Aviation Services (OMAN AIR)','Travel'),
    (3184,'LIAT (LIAT)','Travel'),
    (3185,'LAV Linea Aeropostal Venezolana (LAV)','Travel'),
    (3186,'LAP Lineas Aereas Paraguayas (LAP)','Travel'),
    (3187,'LACSA (Costa Rica) (LACSA)','Travel'),
    (3188,'Virgin Express (VIR EXP)','Travel'),
    (3189,'Авиалинии, авиакомпании','Travel'),
    (3190,'Jugoslav Air (JUGOSLAV)','Travel'),
    (3191,'Island Airlines (ISLANDAI)','Travel'),
    (3192,'Авиалинии, авиакомпании','Travel'),
    (3193,'Indian Airlines (INDIAN A)','Travel'),
    (3194,'Авиалинии, авиакомпании','Travel'),
    (3195,'Авиалинии, авиакомпании','Travel'),
    (3196,'Hawaiian Air (HAWAIIAN)','Travel'),
    (3197,'Havasu Airlines (HAVASUAI)','Travel'),
    (3198,'Авиалинии, авиакомпании','Travel'),
    (3199,'Servicios Aereos Militares','Travel'),
    (3200,'Guyana Airways (GUYANA A)','Travel'),
    (3201,'Авиалинии, авиакомпании','Travel'),
    (3202,'Авиалинии, авиакомпании','Travel'),
    (3203,'Авиалинии, авиакомпании','Travel'),
    (3204,'Freedom Airlines (FREEDOM)','Travel'),
    (3205,'Авиалинии, авиакомпании','Travel'),
    (3206,'China Eastern Airlines (CHINAEAST)','Travel'),
    (3207,'Авиалинии, авиакомпании','Travel'),
    (3208,'Авиалинии, авиакомпании','Travel'),
    (3209,'Авиалинии, авиакомпании','Travel'),
    (3210,'Авиалинии, авиакомпании','Travel'),
    (3211,'Norwegian Air Shuttle (NORWEGIAN)','Travel'),
    (3212,'Dominicana de Aviacion (DOMINICA)','Travel'),
    (3213,'Malmo Aviation (MALMO AV)','Travel'),
    (3214,'Авиалинии, авиакомпании','Travel'),
    (3215,'Авиалинии, авиакомпании','Travel'),
    (3216,'Авиалинии, авиакомпании','Travel'),
    (3217,'CSA Ceskoslovenske Aerolinie (CSA)','Travel'),
    (3218,'Авиалинии, авиакомпании','Travel'),
    (3219,'Compania Panamena de Aviacion (COPA)','Travel'),
    (3220,'Compania Faucett (COMPANIA)','Travel'),
    (3221,'Transportes Aeros Militares Ecuatorianos (TAME AIR)','Travel'),
    (3222,'Command Airways (COMMAND)','Travel'),
    (3223,'Comair (COMAIR)','Travel'),
    (3224,'Авиалинии, авиакомпании','Travel'),
    (3225,'Авиалинии, авиакомпании','Travel'),
    (3226,'Skyways (SKYWAYS)','Travel'),
    (3227,'Авиалинии, авиакомпании','Travel'),
    (3228,'Cayman Airways (CAYMANAIR)','Travel'),
    (3229,'SAETA (Sociedad Ecuatorianas De Transportes Aereo) (SAETAAIR)','Travel'),
    (3230,'Авиалинии, авиакомпании','Travel'),
    (3231,'SAHSA (Servicio Aero de Honduras) (SAHSA)','Travel'),
    (3232,'Авиалинии, авиакомпании','Travel'),
    (3233,'Авиалинии, авиакомпании','Travel'),
    (3234,'Caribbean Airlines (CARIBBEAN)','Travel'),
    (3235,'Авиалинии, авиакомпании','Travel'),
    (3236,'Air Arabia Airline (AIR ARAB)','Travel'),
    (3237,'Авиалинии, авиакомпании','Travel'),
    (3238,'Авиалинии, авиакомпании','Travel'),
    (3239,'Bar Harbor Airlines (BARHARBO)','Travel'),
    (3240,'Bahamasair (BAHAMASA)','Travel'),
    (3241,'Aviateca (Guatemala) (AVIATECA)','Travel'),
    (3242,'Avensa (AVENSA)','Travel'),
    (3243,'Austrian Air Service (AUSTRAIR)','Travel'),
    (3244,'Авиалинии, авиакомпании','Travel'),
    (3245,'EasyJet (EASYJET)','Travel'),
    (3246,'Ryanair (RYANAIR)','Travel'),
    (3247,'Gol Airlines (GOL)','Travel'),
    (3248,'Tam Airlines (TAM)','Travel'),
    (3249,'Авиалинии, авиакомпании','Travel'),
    (3250,'Авиалинии, авиакомпании','Travel'),
    (3251,'Авиалинии, авиакомпании','Travel'),
    (3252,'ALM Antilean Airlines (ALM)','Travel'),
    (3253,'America West (AMERWEST)','Travel'),
    (3254,'Trump Airline','Travel'),
    (3256,'Alaska Airlines Inc. (ALASKA A)','Travel'),
    (3257,'Авиалинии, авиакомпании','Travel'),
    (3258,'Авиалинии, авиакомпании','Travel'),
    (3259,'Авиалинии, авиакомпании','Travel'),
    (3260,'Spirit Airlines (SPIRIT)','Travel'),
    (3261,'Air China (AIR CHINA)','Travel'),
    (3262,'Авиалинии, авиакомпании','Travel'),
    (3263,'Aero Servicio Carabobo (ASERCA)','Travel'),
    (3264,'Авиалинии, авиакомпании','Travel'),
    (3265,'Авиалинии, авиакомпании','Travel'),
    (3266,'Air Seychelles (AIR SEYC)','Travel'),
    (3267,'Air Panama International (AIR PANA)','Travel'),
    (3268,'Авиалинии, авиакомпании','Travel'),
    (3270,'Авиалинии, авиакомпании','Travel'),
    (3274,'Авиалинии, авиакомпании','Travel'),
    (3275,'Авиалинии, авиакомпании','Travel'),
    (3276,'Авиалинии, авиакомпании','Travel'),
    (3277,'Авиалинии, авиакомпании','Travel'),
    (3278,'Авиалинии, авиакомпании','Travel'),
    (3279,'Авиалинии, авиакомпании','Travel'),
    (3280,'Air Jamaica (AIR JAMA)','Travel'),
    (3281,'Air Djibouti (AIR DJIB)','Travel'),
    (3282,'Air Djibouti (AIR DJIB)','Travel'),
    (3283,'Авиалинии, авиакомпании','Travel'),
    (3284,'Авиалинии, авиакомпании','Travel'),
    (3285,'Aero Peru (AEROPERU)','Travel'),
    (3286,'Aero Nicaraguenses (AERO NIC)','Travel'),
    (3287,'Aero Coach Aviation (AEROCOAC)','Travel'),
    (3288,'Авиалинии, авиакомпании','Travel'),
    (3289,'Авиалинии, авиакомпании','Travel'),
    (3290,'Авиалинии, авиакомпании','Travel'),
    (3291,'Авиалинии, авиакомпании','Travel'),
    (3292,'Cyprus Airways (CYPRUSA)','Travel'),
    (3293,'Ecuatoriana (ECUATORI)','Travel'),
    (3294,'Ethiopian Airlines (ETHIOPIA)','Travel'),
    (3295,'Kenya Airways (KENYAAIR)','Travel'),
    (3296,'Air Berlin (AIRBERLIN)','Travel'),
    (3297,'Tarom Romanian Air Transport (TAROM AIR)','Travel'),
    (3298,'Air Mauritius (AIRMAURI)','Travel'),
    (3299,'Wideroes Flyveselskap (WIDEROES)','Travel'),
    (3300,'Azul Air (AZU)','Travel'),
    (3301,'Wizz Air (W6)','Travel'),
    (3351,'Affiliated Auto Rental','Auto'),
    (3352,'American Intl Rent-a-car','Auto'),
    (3353,'Brooks Rent-a-car','Auto'),
    (3354,'Action Auto Rental','Auto'),
    (3355,'Агентства по аренде автомобилей','Auto'),
    (3356,'Агентства по аренде автомобилей','Auto'),
    (3357,'Hertz Rent-a-car','Auto'),
    (3358,'Агентства по аренде автомобилей','Auto'),
    (3359,'Payless Car Rental','Auto'),
    (3360,'Snappy Car Rental','Auto'),
    (3361,'Airways Rent-a-car','Auto'),
    (3362,'Altra Auto Rental','Auto'),
    (3363,'Агентства по аренде автомобилей','Auto'),
    (3364,'Agency Rent-a-car','Auto'),
    (3365,'Агентства по аренде автомобилей','Auto'),
    (3366,'Budget Rent-a-car','Auto'),
    (3367,'Агентства по аренде автомобилей','Auto'),
    (3368,'Holiday Rent-a-wreck','Auto'),
    (3369,'Агентства по аренде автомобилей','Auto'),
    (3370,'Rent-a-wreck','Auto'),
    (3371,'Агентства по аренде автомобилей','Auto'),
    (3372,'Агентства по аренде автомобилей','Auto'),
    (3373,'Агентства по аренде автомобилей','Auto'),
    (3374,'Агентства по аренде автомобилей','Auto'),
    (3375,'Агентства по аренде автомобилей','Auto'),
    (3376,'Ajax Rent-a-car','Auto'),
    (3377,'Агентства по аренде автомобилей','Auto'),
    (3378,'Агентства по аренде автомобилей','Auto'),
    (3379,'Агентства по аренде автомобилей','Auto'),
    (3380,'Агентства по аренде автомобилей','Auto'),
    (3381,'Europ Car','Auto'),
    (3382,'Агентства по аренде автомобилей','Auto'),
    (3383,'Агентства по аренде автомобилей','Auto'),
    (3384,'Агентства по аренде автомобилей','Auto'),
    (3385,'Tropical Rent-a-car','Auto'),
    (3386,'Showcase Rental Cars','Auto'),
    (3387,'Alamo Rent-a-car','Auto'),
    (3388,'Агентства по аренде автомобилей','Auto'),
    (3389,'Avis Rent-a-car','Auto'),
    (3390,'Dollar Rent-a-car','Auto'),
    (3391,'Europe By Car','Auto'),
    (3392,'Агентства по аренде автомобилей','Auto'),
    (3393,'National Car Rental','Auto'),
    (3394,'Kemwell Group Rent-a-car','Auto'),
    (3395,'Thrifty Rent-a-car','Auto'),
    (3396,'Tilden Tent-a-car','Auto'),
    (3397,'Агентства по аренде автомобилей','Auto'),
    (3398,'Econo-car Rent-a-car','Auto'),
    (3399,'Amerex Rent-a-Car','Auto'),
    (3400,'Auto Host Cost Car Rentals','Auto'),
    (3401,'Агентства по аренде автомобилей','Auto'),
    (3402,'Агентства по аренде автомобилей','Auto'),
    (3403,'Агентства по аренде автомобилей','Auto'),
    (3404,'Агентства по аренде автомобилей','Auto'),
    (3405,'Enterprise Rent-a-car','Auto'),
    (3406,'Агентства по аренде автомобилей','Auto'),
    (3407,'Агентства по аренде автомобилей','Auto'),
    (3408,'Агентства по аренде автомобилей','Auto'),
    (3409,'General Rent-a-car','Auto'),
    (3410,'Агентства по аренде автомобилей','Auto'),
    (3412,'A-1 Rent-a-car','Auto'),
    (3413,'Агентства по аренде автомобилей','Auto'),
    (3414,'Godfrey Natl Rent-a-car','Auto'),
    (3415,'Агентства по аренде автомобилей','Auto'),
    (3416,'Агентства по аренде автомобилей','Auto'),
    (3417,'Агентства по аренде автомобилей','Auto'),
    (3418,'Агентства по аренде автомобилей','Auto'),
    (3419,'Alpha Rent-a-car','Auto'),
    (3420,'Ansa Intl Rent-a-car','Auto'),
    (3421,'Allstae Rent-a-car','Auto'),
    (3422,'Агентства по аренде автомобилей','Auto'),
    (3423,'Avcar Rent-a-car','Auto'),
    (3425,'Automate Rent-a-car','Auto'),
    (3426,'Агентства по аренде автомобилей','Auto'),
    (3427,'Avon Rent-a-car','Auto'),
    (3428,'Carey Rent-a-car','Auto'),
    (3429,'Insurance Rent-a-car','Auto'),
    (3430,'Major Rent-a-car','Auto'),
    (3431,'Replacement Rent-a-car','Auto'),
    (3432,'Reserve Rent-a-car','Auto'),
    (3433,'Ugly Duckling Rent-a-car','Auto'),
    (3434,'USA Rent-a-car','Auto'),
    (3435,'Value Rent-a-car','Auto'),
    (3436,'Autohansa Rent-a-car','Auto'),
    (3437,'Cite Rent-a-car','Auto'),
    (3438,'Interent Rent-a-car','Auto'),
    (3439,'Milleville Rent-a-car','Auto'),
    (3440,'Via Route Rent-a-Car','Auto'),
    (3441,'Агентства по аренде автомобилей','Auto'),
    (3501,'Holiday Inns','Travel'),
    (3502,'Best Western Hotels','Travel'),
    (3503,'Sheraton Hotels','Travel'),
    (3504,'Hilton Hotels','Travel'),
    (3505,'Forte Hotels','Travel'),
    (3506,'Golden Tulip Hotels','Travel'),
    (3507,'Friendship Inns','Travel'),
    (3508,'Quality Inns','Travel'),
    (3509,'Marriott Hotels','Travel'),
    (3510,'Days Inn','Travel'),
    (3511,'Arabella Hotels','Travel'),
    (3512,'Inter-continental Hotels','Travel'),
    (3513,'Westin Hotels','Travel'),
    (3514,'Отели, мотели, курорты','Travel'),
    (3515,'Rodeway Inns','Travel'),
    (3516,'La Quinta Motor Inns','Travel'),
    (3517,'Americana Hotels','Travel'),
    (3518,'Sol Hotels','Travel'),
    (3519,'Pullman International Hotels','Travel'),
    (3520,'Meridien Hotels','Travel'),
    (3521,'Crest Hotels (see Forte Hotels)','Travel'),
    (3522,'Tokyo Hotel','Travel'),
    (3523,'Pennsula Hotel','Travel'),
    (3524,'Welcomgroup Hotels','Travel'),
    (3525,'Dunfey Hotels','Travel'),
    (3526,'Отели, мотели, курорты','Travel'),
    (3527,'Downtowner-passport Hotel','Travel'),
    (3528,'Red Lion Hotels','Travel'),
    (3529,'Cp Hotels','Travel'),
    (3530,'Renaissance Hotels','Travel'),
    (3531,'Astir Hotels','Travel'),
    (3532,'Sun Route Hotels','Travel'),
    (3533,'Hotel Ibis','Travel'),
    (3534,'Southern Pacific Hotels','Travel'),
    (3535,'Hilton International','Travel'),
    (3536,'Amfac Hotels','Travel'),
    (3537,'Ana Hotel','Travel'),
    (3538,'Concorde Hotels','Travel'),
    (3539,'Отели, мотели, курорты','Travel'),
    (3540,'Iberotel Hotels','Travel'),
    (3541,'Hotel Okura','Travel'),
    (3542,'Royal Hotels','Travel'),
    (3543,'Four Seasons Hotels','Travel'),
    (3544,'Ciga Hotels','Travel'),
    (3545,'Shangri-la International','Travel'),
    (3546,'Отели, мотели, курорты','Travel'),
    (3547,'Отели, мотели, курорты','Travel'),
    (3548,'Hoteles Melia','Travel'),
    (3549,'Auberge Des Governeurs','Travel'),
    (3550,'Regal 8 Inns','Travel'),
    (3551,'Отели, мотели, курорты','Travel'),
    (3552,'Coast Hotels','Travel'),
    (3553,'Park Inns International','Travel'),
    (3554,'Отели, мотели, курорты','Travel'),
    (3555,'Отели, мотели, курорты','Travel'),
    (3556,'Отели, мотели, курорты','Travel'),
    (3557,'Отели, мотели, курорты','Travel'),
    (3558,'Jolly Hotels','Travel'),
    (3559,'Отели, мотели, курорты','Travel'),
    (3560,'Отели, мотели, курорты','Travel'),
    (3561,'Отели, мотели, курорты','Travel'),
    (3562,'Comfort Inns','Travel'),
    (3563,'Journey’s End Motls','Travel'),
    (3564,'Отели, мотели, курорты','Travel'),
    (3565,'Relax Inns','Travel'),
    (3566,'Отели, мотели, курорты','Travel'),
    (3567,'Отели, мотели, курорты','Travel'),
    (3568,'Ladbroke Hotels','Travel'),
    (3569,'Отели, мотели, курорты','Travel'),
    (3570,'Forum Hotels','Travel'),
    (3571,'Отели, мотели, курорты','Travel'),
    (3572,'Miyako Hotels','Travel'),
    (3573,'Sandman Hotels','Travel'),
    (3574,'Venture Inns','Travel'),
    (3575,'Vagabond Hotels','Travel'),
    (3576,'Отели, мотели, курорты','Travel'),
    (3577,'Mandarin Oriental Hotel','Travel'),
    (3578,'Отели, мотели, курорты','Travel'),
    (3579,'Hotel Mercure','Travel'),
    (3580,'Отели, мотели, курорты','Travel'),
    (3581,'Delta Hotel','Travel'),
    (3582,'Отели, мотели, курорты','Travel'),
    (3583,'Sas Hotels','Travel'),
    (3584,'Princess Hotels International','Travel'),
    (3585,'Hungar Hotels','Travel'),
    (3586,'Sokos Hotels','Travel'),
    (3587,'Doral Hotels','Travel'),
    (3588,'Helmsley Hotels','Travel'),
    (3589,'Отели, мотели, курорты','Travel'),
    (3590,'Fairmont Hotels','Travel'),
    (3591,'Sonesta Hotels','Travel'),
    (3592,'Omni Hotels','Travel'),
    (3593,'Cunard Hotels','Travel'),
    (3594,'Отели, мотели, курорты','Travel'),
    (3595,'Hospitality International','Travel'),
    (3596,'Отели, мотели, курорты','Travel'),
    (3597,'Отели, мотели, курорты','Travel'),
    (3598,'Regent International Hotels','Travel'),
    (3599,'Pannonia Hotels','Travel'),
    (3600,'Отели, мотели, курорты','Travel'),
    (3601,'Отели, мотели, курорты','Travel'),
    (3602,'Отели, мотели, курорты','Travel'),
    (3603,'Noah’s Hotels','Travel'),
    (3604,'Отели, мотели, курорты','Travel'),
    (3605,'Отели, мотели, курорты','Travel'),
    (3606,'Отели, мотели, курорты','Travel'),
    (3607,'Отели, мотели, курорты','Travel'),
    (3608,'Отели, мотели, курорты','Travel'),
    (3609,'Отели, мотели, курорты','Travel'),
    (3610,'Отели, мотели, курорты','Travel'),
    (3611,'Отели, мотели, курорты','Travel'),
    (3612,'Movenpick Hotels','Travel'),
    (3613,'Отели, мотели, курорты','Travel'),
    (3614,'Отели, мотели, курорты','Travel'),
    (3615,'Travelodge','Travel'),
    (3616,'Отели, мотели, курорты','Travel'),
    (3617,'Отели, мотели, курорты','Travel'),
    (3618,'Отели, мотели, курорты','Travel'),
    (3619,'Отели, мотели, курорты','Travel'),
    (3620,'Telford International','Travel'),
    (3621,'Отели, мотели, курорты','Travel'),
    (3622,'Merlin Hotels','Travel'),
    (3623,'Dorint Hotels','Travel'),
    (3624,'Отели, мотели, курорты','Travel'),
    (3625,'Hotle Universale','Travel'),
    (3626,'Prince Hotels','Travel'),
    (3627,'Отели, мотели, курорты','Travel'),
    (3628,'Отели, мотели, курорты','Travel'),
    (3629,'Dan Hotels','Travel'),
    (3630,'Отели, мотели, курорты','Travel'),
    (3631,'Отели, мотели, курорты','Travel'),
    (3632,'Отели, мотели, курорты','Travel'),
    (3633,'Rank Hotels','Travel'),
    (3634,'Swissotel','Travel'),
    (3635,'Reso Hotels','Travel'),
    (3636,'Sarova Hotels','Travel'),
    (3637,'Ramada Inns','Travel'),
    (3638,'Ho Jo Inn','Travel'),
    (3639,'Mount Charlotte Thistle','Travel'),
    (3640,'Hyatt Hotel','Travel'),
    (3641,'Sofitel Hotels','Travel'),
    (3642,'Novotel Hotels','Travel'),
    (3643,'Steigenberger Hotels','Travel'),
    (3644,'Econo Lodges','Travel'),
    (3645,'Queens Moat Houses','Travel'),
    (3646,'Swallow Hotels','Travel'),
    (3647,'Husa Hotels','Travel'),
    (3648,'De Vere Hotels','Travel'),
    (3649,'Radisson Hotels','Travel'),
    (3650,'Red Rook Inns','Travel'),
    (3651,'Imperial London Hotel','Travel'),
    (3652,'Embassy Hotels','Travel'),
    (3653,'Penta Hotels','Travel'),
    (3654,'Loews Hotels','Travel'),
    (3655,'Scandic Hotels','Travel'),
    (3656,'Sara Hotels','Travel'),
    (3657,'Oberoi Hotels','Travel'),
    (3658,'Otani Hotels','Travel'),
    (3659,'Taj Hotels International','Travel'),
    (3660,'Knights Inns','Travel'),
    (3661,'Metropole Hotels','Travel'),
    (3662,'Отели, мотели, курорты','Travel'),
    (3663,'Hoteles El Presidents','Travel'),
    (3664,'Flag Inn','Travel'),
    (3665,'Hampton Inns','Travel'),
    (3666,'Stakis Hotels','Travel'),
    (3667,'Отели, мотели, курорты','Travel'),
    (3668,'Maritim Hotels','Travel'),
    (3669,'Отели, мотели, курорты','Travel'),
    (3670,'Arcard Hotels','Travel'),
    (3671,'Arctia Hotels','Travel'),
    (3672,'Campaniel Hotels','Travel'),
    (3673,'Ibusz Hotels','Travel'),
    (3674,'Rantasipi Hotels','Travel'),
    (3675,'Interhotel Cedok','Travel'),
    (3676,'Отели, мотели, курорты','Travel'),
    (3677,'Climat De France Hotels','Travel'),
    (3678,'Cumulus Hotels','Travel'),
    (3679,'Danubius Hotel','Travel'),
    (3680,'Отели, мотели, курорты','Travel'),
    (3681,'Adams Mark Hotels','Travel'),
    (3682,'Allstar Inns','Travel'),
    (3683,'Отели, мотели, курорты','Travel'),
    (3684,'Budget Host Inns','Travel'),
    (3685,'Budgetel Hotels','Travel'),
    (3686,'Suisse Chalets','Travel'),
    (3687,'Clarion Hotels','Travel'),
    (3688,'Compri Hotels','Travel'),
    (3689,'Consort Hotels','Travel'),
    (3690,'Courtyard By Marriott','Travel'),
    (3691,'Dillion Inns','Travel'),
    (3692,'Doubletree Hotels','Travel'),
    (3693,'Drury Inns','Travel'),
    (3694,'Economy Inns Of America','Travel'),
    (3695,'Embassy Suites','Travel'),
    (3696,'Exel Inns','Travel'),
    (3697,'Farfield Hotels','Travel'),
    (3698,'Harley Hotels','Travel'),
    (3699,'Midway Motor Lodge','Travel'),
    (3700,'Motel 6','Travel'),
    (3701,'Guest Quarters (formally Pickett Suite Hotels)','Travel'),
    (3702,'The Registry Hotels','Travel'),
    (3703,'Residence Inns','Travel'),
    (3704,'Royce Hotels','Travel'),
    (3705,'Sandman Inns','Travel'),
    (3706,'Shilo Inns','Travel'),
    (3707,'Shoney’s Inns','Travel'),
    (3708,'Отели, мотели, курорты','Travel'),
    (3709,'Super8 Motels','Travel'),
    (3710,'The Ritz Carlton Hotels','Travel'),
    (3711,'Flag Inns (Ausralia)','Travel'),
    (3712,'Golden Chain Hotel','Travel'),
    (3713,'Quality Pacific Hotel','Travel'),
    (3714,'Four Seasons Hotel (Australia)','Travel'),
    (3715,'Farifield Inn','Travel'),
    (3716,'Carlton Hotels','Travel'),
    (3717,'City Lodge Hotels','Travel'),
    (3718,'Karos Hotels','Travel'),
    (3719,'Protea Hotels','Travel'),
    (3720,'Southern Sun Hotels','Travel'),
    (3721,'Hilton Conrad','Travel'),
    (3722,'Wyndham Hotel And Resorts','Travel'),
    (3723,'Rica Hotels','Travel'),
    (3724,'Iner Nor Hotels','Travel'),
    (3725,'Seaines Planation','Travel'),
    (3726,'Rio Suites','Travel'),
    (3727,'Broadmoor Hotel','Travel'),
    (3728,'Bally’s Hotel And Casino','Travel'),
    (3729,'John Ascuaga’s Nugget','Travel'),
    (3730,'Mgm Grand Hotel','Travel'),
    (3731,'Harrah’s Hotels And Casinos','Travel'),
    (3732,'Opryland Hotel','Travel'),
    (3733,'Boca Raton Resort','Travel'),
    (3734,'Harvey/bristol Hotels','Travel'),
    (3735,'Отели, мотели, курорты','Travel'),
    (3736,'Colorado Belle/Edgewater Resort','Travel'),
    (3737,'Riviera Hotel And Casino','Travel'),
    (3738,'Tropicana Resort And Casino','Travel'),
    (3739,'Woodside Hotels And Resorts','Travel'),
    (3740,'Townplace Suites','Travel'),
    (3741,'Millenium Broadway Hotel','Travel'),
    (3742,'Club Med','Travel'),
    (3743,'Biltmore Hotel And Suites','Travel'),
    (3744,'Carefree Resorts','Travel'),
    (3745,'St. Regis Hotel','Travel'),
    (3746,'The Eliot Hotel','Travel'),
    (3747,'Clubcorp/club Resorts','Travel'),
    (3748,'Welesley Inns','Travel'),
    (3749,'The Beverly Hills Hotel','Travel'),
    (3750,'Crowne Plaza Hotels','Travel'),
    (3751,'Homewood Suites','Travel'),
    (3752,'Peabody Hotels','Travel'),
    (3753,'Greenbriah Resorts','Travel'),
    (3754,'Amelia Island Planation','Travel'),
    (3755,'The Homestead','Travel'),
    (3756,'South Seas Resorts','Travel'),
    (3757,'Отели, мотели, курорты','Travel'),
    (3758,'Отели, мотели, курорты','Travel'),
    (3759,'Отели, мотели, курорты','Travel'),
    (3760,'Отели, мотели, курорты','Travel'),
    (3761,'Отели, мотели, курорты','Travel'),
    (3762,'Отели, мотели, курорты','Travel'),
    (3763,'Отели, мотели, курорты','Travel'),
    (3764,'Отели, мотели, курорты','Travel'),
    (3765,'Отели, мотели, курорты','Travel'),
    (3766,'Отели, мотели, курорты','Travel'),
    (3767,'Отели, мотели, курорты','Travel'),
    (3768,'Отели, мотели, курорты','Travel'),
    (3769,'Отели, мотели, курорты','Travel'),
    (3770,'Отели, мотели, курорты','Travel'),
    (3771,'Отели, мотели, курорты','Travel'),
    (3772,'Отели, мотели, курорты','Travel'),
    (3773,'Отели, мотели, курорты','Travel'),
    (3774,'Отели, мотели, курорты','Travel'),
    (3775,'Отели, мотели, курорты','Travel'),
    (3776,'Отели, мотели, курорты','Travel'),
    (3777,'Отели, мотели, курорты','Travel'),
    (3778,'Отели, мотели, курорты','Travel'),
    (3779,'Отели, мотели, курорты','Travel'),
    (3780,'Отели, мотели, курорты','Travel'),
    (3781,'Отели, мотели, курорты','Travel'),
    (3782,'Отели, мотели, курорты','Travel'),
    (3783,'Отели, мотели, курорты','Travel'),
    (3784,'Отели, мотели, курорты','Travel'),
    (3785,'Отели, мотели, курорты','Travel'),
    (3786,'Отели, мотели, курорты','Travel'),
    (3787,'Отели, мотели, курорты','Travel'),
    (3788,'Отели, мотели, курорты','Travel'),
    (3789,'Отели, мотели, курорты','Travel'),
    (3790,'Отели, мотели, курорты','Travel'),
    (3791,'Отели, мотели, курорты','Travel'),
    (3792,'Отели, мотели, курорты','Travel'),
    (3793,'Отели, мотели, курорты','Travel'),
    (3794,'Отели, мотели, курорты','Travel'),
    (3795,'Отели, мотели, курорты','Travel'),
    (3796,'Отели, мотели, курорты','Travel'),
    (3797,'Отели, мотели, курорты','Travel'),
    (3798,'Отели, мотели, курорты','Travel'),
    (3799,'Отели, мотели, курорты','Travel'),
    (3816,'Home2Suites','Travel'),
    (3828,'Cosmopolitan of Las Vegas','Travel'),
    (3830,'Park Plaza Hotel','Travel'),
    (3831,'Waldorf','Travel'),
    (3832,'Curio Hotels','Travel'),
    (3833,'Canopy','Travel'),
    (3834,'Baymont Inn & Suites','Travel'),
    (3835,'Dolce Hotels and Resorts','Travel'),
    (3836,'Hawthorn by Wyndham','Travel'),
    (3882,'Инкассация чека (обналичивание)',''),
    (4011,'Железные дороги – перевозка грузов','Travel'),
    (4111,'Пассажирские перевозки - пригородные и местные пригородные рейсы, включая паромы','Travel'),
    (4112,'Пассажирские железнодорожные перевозки','Travel'),
    (4119,'Услуги скорой помощи','Beauty and medicine'),
    (4121,'Лимузины и такси','Taxi'),
    (4131,'Автобусные линии','Travel'),
    (4214,'Агентства по автотранспортным перевозкам, местные/ дальные автогрузоперевозки, компании попереезду и хранению, местная доставка','Travel'),
    (4215,'Услуги курьера – по воздуху и на земле, агентство по отправке грузов','Other'),
    (4225,'Складское хранение общественного пользования –сельскохозяйственных продуктов, охлаждаемые продукты, хранение предметов домашнего обихода','Products and supermarkets'),
    (4304,'Категория неизвестна','Other'),
    (4411,'Круизные линии','Travel'),
    (4457,'Аренда и наем суден','Travel'),
    (4468,'Пристани для яхт, их обслуживание и поставка','Travel'),
    (4511,'Авиалинии, авиакомпании - нигде более не классифицированные','Travel'),
    (4582,'Аэропорты, терминалы аэропортов, лётные поля','Travel'),
    (4722,'Туристические агентства и организаторы экскурсий','Travel'),
    (4723,'Пакетные туроператоры - только Германия','Travel'),
    (4729,'Услуги пассажирских перевозок – нигде более не классифицированные','Travel'),
    (4784,'Дорожный и мостовой сборы, пошлины','Travel'),
    (4785,'Категория неизвестна','Other'),
    (4789,'Услуги пассажирских перевозок – нигде более не классифицированные','Travel'),
    (4812,'Телекоммуникационное оборудование, включая продажу телефонов','Mobile'),
    (4813,'Торговые точки телеком клавишного ввода, предлагающие единичные локальные и дальние телефонные звонки, используя центральный номер доступа без разговора с оператором и используя код доступа','Mobile'),
    (4814,'Телекоммуникационные услуги','Mobile'),
    (4815,'МастерФон телефонные услуги – Ежемесячное составление телефонных счетов','Mobile'),
    (4816,'Компьютерные сети, информационные услуги','Mobile'),
    (4821,'Услуги телеграфа','Mobile'),
    (4829,'Денежные переводы',''),
    (4899,'Кабельные и другие платные телевизионные услуги','Dormitory and Internet'),
    (4900,'Коммунальные услуги – электричество, газ, канализация, вода','Dormitory and Internet'),
    (5013,'Поставщики грузовиков и запчастей','Dormitory and Internet'),
    (5021,'Офисная и торговая мебель','Dormitory and Internet'),
    (5039,'Строительные материалы – нигде более не классифицированные','Repair'),
    (5044,'Офисное, фотографическое, фотокопировальное, и микрофильмирующее оборудование','Dormitory and Internet'),
    (5045,'Компьютеры, периферийное компьютерное оборудование, программное обеспечение','Household appliances'),
    (5046,'Коммерческое оборудование – нигде более не классифицированное','Household appliances'),
    (5047,'Стоматологическое / лабораторное / медицинское / офтальмологическое оборудование и материалы для больниц','Beauty and medicine'),
    (5051,'Центры и офисы работ по металлу','Repair'),
    (5065,'Электрические части и оборудование','Repair'),
    (5072,'Оборудование и сопутствующие материалы для технического обеспечения','Repair'),
    (5074,'Оборудование для водопровода и отопительной системы','Repair'),
    (5085,'Промышленное оборудование –нигде более не классифицированное','Repair'),
    (5094,'Драгоценные камни и металлы, часы и ювелирные изделия','Other'),
    (5099,'Товары длительного пользования – нигде более не классифицированные','Other'),
    (5111,'Канцелярия, офисные сопутствующие товары, бумага для печатания и письма','Products and supermarkets'),
    (5122,'Лекарства, их распространители, аптеки','Beauty and medicine'),
    (5131,'Штучные товары, галантерея и другие текстильные товары','Clothing and footwear'),
    (5137,'Мужская, женская и детская спецодежда','Clothing and footwear'),
    (5139,'Спец-обувь','Clothing and footwear'),
    (5169,'Химикалии и смежные вещества - нигде более не классифицированные','Other'),
    (5172,'Нефть и нефтепродукты','Auto'),
    (5192,'Книги, периодические издания и газеты','Other'),
    (5193,'Принадлежности для флористов, питомник и цветы','Flowers'),
    (5198,'Лакокрасочная продукция и сопровождающие товары','Repair'),
    (5199,'Товары недлительного пользования - нигде более не классифицированные','Other'),
    (5200,'Товары для дома','Dormitory and Internet'),
    (5211,'Лесо- и строительный материал','Dormitory and Internet'),
    (5231,'Розничная продажа стекла, красок и обоев','Dormitory and Internet'),
    (5251,'Скобяные товары в розницу','Dormitory and Internet'),
    (5261,'Садовые принадлежности (в том числе для ухода за газонами) в розницу','Dormitory and Internet'),
    (5271,'Продажа жилых фургонов','Other'),
    (5292,'Категория неизвестна','Other'),
    (5295,'Категория неизвестна','Other'),
    (5297,'Retail Internet Volume','Products and supermarkets'),
    (5298,'Internet Shopping Grocery Store','Products and supermarkets'),
    (5300,'Оптовики','Products and supermarkets'),
    (5309,'Беспошлинные магазины Duty Free','Duty Free'),
    (5310,'Магазины, торгующие по сниженным ценам','Products and supermarkets'),
    (5311,'Универмаги','Products and supermarkets'),
    (5331,'Универсальные магазины','Products and supermarkets'),
    (5399,'Различные товары общего назначения','Products and supermarkets'),
    (5411,'Бакалейные магазины, супермаркеты','Products and supermarkets'),
    (5412,'Гибридные супермаркеты','Products and supermarkets'),
    (5415,'Категория неизвестна','Other'),
    (5422,'Продажа свежего и мороженого мяса','Products and supermarkets'),
    (5441,'Кондитерские','Products and supermarkets'),
    (5451,'Продажа молочных продуктов в розницу','Products and supermarkets'),
    (5462,'Булочные','Products and supermarkets'),
    (5499,'Различные продовольственные магазины - нигде более не классифицированные','Products and supermarkets'),
    (5511,'Легковой и грузовой транспорт – продажа, сервис, ремонт, запчасти и лизинг.','Auto'),
    (5521,'Продажа легковых и грузовых автомобилей (только подержанных)','Auto'),
    (5531,'Автомагазины и товары для дома','Auto'),
    (5532,'Автошины','Auto'),
    (5533,'Автозапчасти и аксессуары','Auto'),
    (5541,'Заправочные станции (с вспомогательными услугами или без)','Auto'),
    (5542,'Автоматические заправочные станции','Auto'),
    (5551,'Продажа лодок','Auto'),
    (5561,'Дома- автоприцепы, жилые неразборные и грузовые прицепы','Auto'),
    (5571,'Продажа мотоциклов','Auto'),
    (5592,'Продажа домов на колесах','Auto'),
    (5598,'Продажа снегоходов','Auto'),
    (5599,'Продажа различного рода автомобилей, авиа- и с/х оборудования - нигде более не классифицированные','Auto'),
    (5611,'Мужская одежда и аксессуары, включая одежду для мальчиков','Clothing and footwear'),
    (5621,'Готовая женская одежда','Clothing and footwear'),
    (5631,'Аксессуары для женщин','Clothing and footwear'),
    (5641,'Детская одежда, включая одежду для самых маленьких','Clothing and footwear'),
    (5651,'Одежда для всей семьи','Clothing and footwear'),
    (5655,'Спортивная одежда, одежда для верховой езды и езды на мотоцикле','Clothing and footwear'),
    (5661,'Обувные магазины','Clothing and footwear'),
    (5681,'Изготовление и продажа меховых изделий','Clothing and footwear'),
    (5691,'Магазины мужской и женской одежды','Clothing and footwear'),
    (5697,'Услуги по переделке, починке и пошиву одежды','Clothing and footwear'),
    (5698,'Парики и накладки из искусственных волос','Clothing and footwear'),
    (5699,'Различные магазины одежды и аксессуаров','Clothing and footwear'),
    (5712,'Оборудование, мебель и бытовые принадлежности (кроме электрооборудования)','Repair'),
    (5713,'Покрытия для пола','Repair'),
    (5714,'Ткани, обивочный материал, гардины и портьеры, жалюзи','Repair'),
    (5715,'Оптовые продавцы алкоголя','Products and supermarkets'),
    (5718,'Продажа каминов, экранов для каминов и аксессуаров','Repair'),
    (5719,'Различные специализированные магазины бытовых принадлежностей','Household appliances'),
    (5722,'Бытовое оборудование','Household appliances'),
    (5732,'Продажа электронного оборудования','Household appliances'),
    (5733,'Продажа музыкальных инструментов, фортепиано, нот.','Household appliances'),
    (5734,'Продажа компьютерного программного обеспечения','Household appliances'),
    (5735,'Магазины звукозаписи','Household appliances'),
    (5811,'Поставщики провизии','Cafes and restaurants'),
    (5812,'Места общественного питания, рестораны','Cafes and restaurants'),
    (5813,'Бары, коктейль-бары, дискотеки, ночные клубы и таверны – места продажи алкогольных напитков','Cafes and restaurants'),
    (5814,'Фастфуд','Cafes and restaurants'),
    (5815,'Цифровые товары - аудиовизуальные медиа, включая книги, фильмы и музыку','Dormitory and Internet'),
    (5816,'Цифровые товары – игры','Dormitory and Internet'),
    (5817,'Цифровые товары - приложения (кроме игр)','Dormitory and Internet'),
    (5818,'Цифровые товары - мультикатегория','Dormitory and Internet'),
    (5912,'Аптеки','Beauty and medicine'),
    (5921,'Магазины с продажей спиртных напитков навынос','Cafes and restaurants'),
    (5931,'Секонд-хенды, магазины б/у товаров, комиссионки','Clothing and footwear'),
    (5932,'Антикварные магазины – продажа, ремонт и услуги реставрации','Other'),
    (5933,'Ломбарды','Other'),
    (5935,'Уничтожение и сбор остатков','Other'),
    (5937,'Магазины репродукций и антиквариата','Other'),
    (5940,'Веломагазины – продажа и обслуживание','Entertainment and sports'),
    (5941,'Спорттовары','Entertainment and sports'),
    (5942,'Книжные магазины','Books'),
    (5943,'Магазины офисных, школьных принадлежностей, канцтоваров','Books'),
    (5944,'Часы, ювелирные и серебряные изделия','Other'),
    (5945,'Игрушки, игры и хобби-товары','Entertainment and sports'),
    (5946,'Магазины фотооборудования и фотоприборов','Household appliances'),
    (5947,'Магазины открыток, подарков, новинок и сувениров','Other'),
    (5948,'Магазины кожаных изделий, дорожных принадлежностей','Other'),
    (5949,'Магазины ткани, ниток, рукоделия, шитья','Other'),
    (5950,'Магазины хрусталя и изделий из стекла','Other'),
    (5960,'Прямой маркетинг – страховые услуги','Other'),
    (5961,'Заказы по почте, включая заказы по каталогу','Other'),
    (5962,'Прямой маркетинг – услуги, относящиеся к туризму','Other'),
    (5963,'Продажа "от двери до двери"','Other'),
    (5964,'Прямой маркетинг – торговля по каталогам','Other'),
    (5965,'Прямой маркетинг – комбинированный каталог и розничные продавцы','Other'),
    (5966,'Прямой маркетинг - исходящий телемаркетинг','Other'),
    (5967,'Прямой маркетинг – входящий телемаркетинг','Other'),
    (5968,'Прямой маркетинг – Торговые точки подписки','Other'),
    (5969,'Прямой маркетинг – другие торговые точки прямого маркетинга (нигде более не классифицированные)','Other'),
    (5970,'Магазины художественных и ремесляных изделий','Other'),
    (5971,'Галереи и художественные посредники','Other'),
    (5972,'Магазины монет и марок (филателические и нумизматические)','Other'),
    (5973,'Магазины религиозных товаров','Other'),
    (5975,'Слуховые аппараты – продажа, сервис, снабжение','Other'),
    (5976,'Ортопедические товары','Other'),
    (5977,'Магазины косметики','Beauty and medicine'),
    (5978,'Магазины печатающих устройств – аренда, продажа, услуги','Other'),
    (5983,'Поставщики топлива – уголь, мазут, сжиженная нефть, древесина','Other'),
    (5992,'Флористика','Flowers'),
    (5993,'Табачные магазины','Other'),
    (5994,'Дилеры по продаже печатной продукции','Other'),
    (5995,'Зоомагазины','Animals'),
    (5996,'Плавательные бассейны – продажа и снабжение','Other'),
    (5997,'Магазины электрических бритвенных принадлежностей – распродажа и услуги.','Other'),
    (5998,'Магазины палаток и навесов','Entertainment and sports'),
    (5999,'Различные магазины и специальные розничные магазины','Other'),
    (6010,'Финансовые учреждения – снятие наличности вручную',''),
    (6011,'Финансовые учреждения – снятие наличности автоматически',''),
    (6012,'Финансовые учреждения – торговля и услуги',''),
    (6022,'Financial Institution (RCL Internal)','Other'),
    (6023,'State Banks (RCL Internal)','Other'),
    (6025,'National Banks (RCL Internal)','Other'),
    (6026,'National Banks Non Federal (RCL Internal)','Other'),
    (6028,'Unincorporated Private Banks (RCL Internal)','Other'),
    (6050,'Финансовые учреждения – квази-кэш (электронные деньги)','Other'),
    (6051,'Нефинансовые учреждения – квази-кэш','Other'),
    (6211,'Ценные бумаги – Брокеры/Дилеры','Other'),
    (6300,'Продажа страхования, андеррайтинг, премии','Other'),
    (6381,'Страховые премии','Other'),
    (6399,'Страхование - нигде более не классифицированные','Other'),
    (6513,'Агенты недвижимости и менеджеры - Аренда','Other'),
    (6529,'Remote Stored Value Load - Финансовые организации','Other'),
    (6530,'Remote Stored Value Load - Продавец','Other'),
    (6531,'Оплата услуг – денежные переводы','Other'),
    (6532,'Платежная операция - финансовое учреждение','Other'),
    (6533,'Платежная операция - продавец','Other'),
    (6534,'Денежный перевод - финансовое учреждение','Other'),
    (6535,'Права требования на ценности — Финансовые организации','Other'),
    (6536,'Денежные переводы MasterCard MoneySend - внутри страны','Other'),
    (6537,'Денежные переводы MasterCard MoneySend - между странами','Other'),
    (6538,'Денежные переводы MasterCard MoneySend Funding','Other'),
    (6539,'Транзакция по финансированию (исключая MoneySend)','Other'),
    (6540,'Транзакции по финансированию POI (за исключением MoneySend)','Other'),
    (6611,'Переплата (авансовые платежи)','Other'),
    (6760,'Облигации сберегательного займа','Other'),
    (7011,'Отели и мотели - нигде более не классифицированные','Travel'),
    (7012,'Тайм-шер','Other'),
    (7032,'Рекреационные и спортивные лагеря','Entertainment and sports'),
    (7033,'Кемпинги и трейлер-парки','Entertainment and sports'),
    (7210,'Услуги по уборке и прачечной','Other'),
    (7211,'Услуги прачечной - семейные и коммерческие','Other'),
    (7216,'Химчистка','Other'),
    (7217,'Чистка ковров и обивок','Other'),
    (7221,'Фотостудии','Other'),
    (7230,'Парикмахерские и салоны красоты','Beauty and medicine'),
    (7251,'Чистка шляп, ремонт и чистка обуви','Other'),
    (7261,'Похоронные службы и крематории','Other'),
    (7273,'Знакомства','Other'),
    (7276,'Служба налоговой подготовки','Other'),
    (7277,'Долги, брак, личные вопросы - консультирование','Other'),
    (7278,'Услуги покупок/шоппинга','Other'),
    (7280,'Пациент больницы – вывод личных средств','Other'),
    (7296,'Сдача в аренду костюмов, униформы, простой одежды','Other'),
    (7297,'Массажные салоны','Beauty and medicine'),
    (7298,'Салоны красоты и здоровья','Beauty and medicine'),
    (7299,'Различные услуги - нигде более не классифицированные','Other'),
    (7311,'Рекламные услуги','Other'),
    (7321,'Потребительские кредитные агентства','Other'),
    (7322,'Агентства взыскания долгов','Other'),
    (7332,'Услуги синьки и фотокопирования','Other'),
    (7333,'Коммерческое искусство, графика, фотография','Other'),
    (7338,'Быстрое копирование, репродуцирование и услуги по созданию чертежей','Other'),
    (7339,'Услуги стенографии и секретарского дела','Other'),
    (7342,'Истребление насекомых и дезинфекция','Other'),
    (7349,'Уборка и чистка помещений','Dormitory and Internet'),
    (7361,'Агентства по трудоустройству, временные справочные службы','Other'),
    (7372,'Программирование, обработка данных, проектирование интегрированных систем','Other'),
    (7375,'Информационно-поисковые услуги','Other'),
    (7379,'Ремонт компьютеров','Other'),
    (7389,'Бизнес услуги – нигде более не классифицированные','Other'),
    (7392,'Услуги по консультированию, управлению и связям с общественностью','Other'),
    (7393,'Детективные агентства, охранные агентства, службы безопасности, включая бронированные автомобили, сторожевых собак','Other'),
    (7394,'Аренда оборудования и лизинговые услуги, аренда мебели, прокат инструментов','Other'),
    (7395,'Фотостудии, фотолаборатории','Other'),
    (7399,'Бизнес услуги – нигде более не классифицированные','Other'),
    (7511,'Стоянка грузового транспорта','Auto'),
    (7512,'Прокат автомобилей','Auto'),
    (7513,'Прокат аксессуаров для трэйлеров и грузовиков.','Auto'),
    (7519,'Прокат домиков на колесах, аксессуары к наземному транспорту.','Auto'),
    (7523,'Паркинги и гаражи','Auto'),
    (7531,'Станции технического обслуживания для автомобильного транспорта','Auto'),
    (7534,'Шиномонтаж и вулканизация','Auto'),
    (7535,'Покраска автомобилей','Auto'),
    (7538,'СТО общего назначения','Auto'),
    (7542,'Автомойки','Auto'),
    (7549,'Буксировка','Auto'),
    (7622,'Ремонт электроники','Other'),
    (7623,'Ремонт кондиционеров и холодильников','Other'),
    (7629,'Ремонт электрооборудования и малой бытовой техники','Other'),
    (7631,'Центры ремонта часов и чистки ювелирных изделий','Other'),
    (7641,'Мебель – обивка, ремонт и реставрация','Other'),
    (7692,'Ремонт с помощью сварки','Other'),
    (7699,'Ремонтные услуги – нигде более не классифицированные','Other'),
    (7800,'Правительственная лотерея (только США)','Other'),
    (7801,'Азартные игры в интернете (только США)','Other'),
    (7802,'Лошадиные / собачьи бега (только США)','Other'),
    (7829,'Производство фото/видео','Other'),
    (7832,'Кинотеатры','Cinema'),
    (7833,'Экспресс-оплата – Кинотеатр','Cinema'),
    (7841,'Видеопрокат','Entertainment and sports'),
    (7911,'Танцклубы, танцшколы и студии','Entertainment and sports'),
    (7922,'Театральные продюсеры (кроме кинофильмов), билетные агентства','Other'),
    (7929,'Музыкальные группы, оркестры и прочие развлекательные услуги','Other'),
    (7932,'Бильярд-клубы','Other'),
    (7933,'Боулинг-клубы','Other'),
    (7941,'Атлетические поля, коммерческие виды спорта, профессиональные спортивные клубы, промоутеры спорта','Entertainment and sports'),
    (7991,'Туристические аттракционы и шоу','Entertainment and sports'),
    (7992,'Публичные поля для гольфа','Entertainment and sports'),
    (7993,'Принадлежности для видеоигр','Entertainment and sports'),
    (7994,'Галереи/учреждения видеоигр','Entertainment and sports'),
    (7995,'Транзакции по азартным играм','Entertainment and sports'),
    (7996,'Парки аттракционов, карнавалы, цирки, гадалки','Entertainment and sports'),
    (7997,'Клубы – загородные клубы, членство (отдых, спорт), частные поля для гольфа','Entertainment and sports'),
    (7998,'Аквариумы, дельфинарии, зоопарки и морские парки','Entertainment and sports'),
    (7999,'Услуги отдыха — нигде более не классифицированные','Entertainment and sports'),
    (8011,'Доктора — нигде более не классифицированные','Beauty and medicine'),
    (8021,'Дантисты, ортодантисты','Beauty and medicine'),
    (8031,'Остеопаты','Beauty and medicine'),
    (8041,'Хиропрактики','Beauty and medicine'),
    (8042,'Оптометристы, офтальмологи','Beauty and medicine'),
    (8043,'Оптика, оптические товары и очки','Beauty and medicine'),
    (8044,'Оптика, оптические товары и очки','Beauty and medicine'),
    (8049,'Ортопеды','Beauty and medicine'),
    (8050,'Услуги персонального ухода','Beauty and medicine'),
    (8062,'Больницы','Beauty and medicine'),
    (8071,'Стоматологические и медицинские лаборатории','Beauty and medicine'),
    (8099,'Медицинские работники, медицинские услуги – нигде более не классифицированные','Beauty and medicine'),
    (8111,'Адвокаты, юридические услуги','Other'),
    (8211,'Начальная и средняя школы','Other'),
    (8220,'Колледжи, университеты','Other'),
    (8241,'Дистанционные школы','Other'),
    (8244,'Бизнес / секретарские школы','Other'),
    (8249,'Профессиональные / торговые школы','Other'),
    (8299,'Образовательные услуги','Other'),
    (8351,'Дошкольные заведения','Other'),
    (8398,'Благотворительные и общественные службы - сбор средств','Other'),
    (8641,'Гражданские, социальные и братские ассоциации','Other'),
    (8651,'Политические организации','Other'),
    (8661,'Религиозные организации','Other'),
    (8664,'Категория неизвестна','Other'),
    (8675,'Автомобильные ассоциации','Other'),
    (8699,'Членские организации – нигде более не классифицированные','Other'),
    (8734,'Испытательные лаборатории (немедицинские)','Other'),
    (8911,'Архитектурные, инженерные и геодезические услуги','Other'),
    (8931,'Бухгалтерский учет, аудит и бухгалтерские услуги','Other'),
    (8999,'Профессиональные услуги - нигде более не классифицированные','Other'),
    (9034,'I-Purchasing Pilot','Other'),
    (9211,'Судебные выплаты, включая алименты и детскую поддержку','Budget and taxes'),
    (9222,'Штрафы','Budget and taxes'),
    (9223,'Платежи по залогам и облигациям','Budget and taxes'),
    (9311,'Налоговые платежи','Budget and taxes'),
    (9399,'Правительственные услуги - нигде более не классифицированные','Other'),
    (9401,'I-Purchasing Pilot','Other'),
    (9402,'Почтовые услуги (только правительственные)','Other'),
    (9405,'Внутриправительственные закупки - только правительственные','Other'),
    (9411,'Платежи по государственному займу','Other'),
    (9700,'Automated Referral Service (только VISA)','Other'),
    (9701,'Служба проверки учетных данных Visa (только VISA)','Other'),
    (9702,'Аварийные службы (GCAS) (только VISA)','Other'),
    (9751,'Великобритания. Универсамы. Электронный Горячий Файл','Other'),
    (9752,'Британские Бензозаправочные станции. Электронный Горячий Файл','Other'),
    (9754,'Лошадиные / собачьи бега (только США)','Other'),
    (9950,'Покупки внутри компании','Other'),
    (9999,'Категория неизвестна','Other');

-- -----------------------------------------------------
-- Insert demo data
-- -----------------------------------------------------
INSERT INTO user (username, email, password, name, surname, enabled) VALUES
    ('demo', 'demo@demo.com', '$2a$10$iQXJ7lGfanJdq8.qUEoRq.US4MZzlA4at5XHfzgqQWICp8hQVZp9O', 'Demo', 'Demonov', 1);
INSERT INTO authority (username, authority) VALUES ('demo', 'ROLE_USER');

INSERT INTO account (type, summary, description, username, currency_code) VALUES
    ('Cash', 0.0, 'Cash in wallet', 'demo', 'UAH'),
    ('Debit Card', 0.0, 'Salary debit card', 'demo', 'UAH'),
    ('USD Deposit', 9660.45, 'Foreign Currency Deposit', 'demo', 'USD');

INSERT INTO category (name, description, username, income) VALUES
    ('Salary', 'Salary category', 'demo', 1),
    ('Gifts', 'Gifts category', 'demo', 1),
    ('Deposit Profit', '', 'demo', 1),
    ('Other', '', 'demo', 1),
    ('Apartment Rent', '', 'demo', 0),
    ('Food', 'Food category', 'demo', 0),
    ('Health Care', '', 'demo', 0),
    ('Mobile and Internet', '', 'demo', 0),
    ('Education', '', 'demo', 0),
    ('Presents', '', 'demo', 0),
    ('Amusement', '', 'demo', 0),
    ('Clothes', '', 'demo', 0),
    ('Travel', '', 'demo', 0);

INSERT INTO expense (sum, category_id, date, time, comment, username, account_id, currency_code) VALUES
    (
        48.30,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-01-02',
        '10:00:00',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        48.54,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-02-01',
        '12:32:13',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        48.79,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-03-01',
        '16:02:54',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        49.03,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-04-01',
        '07:50:50',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        49.28,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-05-01',
        '22:14:43',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        49.52,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-06-01',
        '10:34:23',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        49.77,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-07-01',
        '13:10:30',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        50.02,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-08-01',
        '14:04:09',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        50.27,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-09-01',
        '14:24:36',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        50.52,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-10-01',
        '11:23:40',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        50.77,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-11-01',
        '09:17:48',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    ),
    (
        51.03,
        (SELECT category_id FROM category WHERE name = 'Deposit Profit'),
        '2020-12-01',
        '11:11:11',
        'Deposit profit',
        'demo',
        (SELECT account_id FROM account WHERE type = 'USD Deposit'),
        'USD'
    );

UPDATE account SET summary = (summary + 595.84) WHERE type = 'USD Deposit';

INSERT INTO expense (sum, category_id, date, time, comment, username, account_id, currency_code) VALUES
    (
        53500,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2020-07-05',
        '09:30:13',
        'Salary for June',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        53500,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2020-08-04',
        '09:23:17',
        'Salary for July',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        53500,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2020-09-05',
        '09:31:15',
        'Salary for August',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        53500,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2020-10-05',
        '09:37:03',
        'Salary for September',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        53500,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2020-11-03',
        '09:00:33',
        'Salary for October',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        53500,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2020-12-06',
        '10:03:44',
        'Salary for November',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        96300,
        (SELECT category_id FROM category WHERE name = 'Salary'),
        '2021-01-06',
        '09:22:34',
        'Salary for December + bonus',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    );

UPDATE account SET summary = (summary + 417300) WHERE type = 'Debit Card';
UPDATE account SET summary = (summary - 100000) WHERE type = 'Debit Card';
UPDATE account SET summary = (summary + 100000) WHERE type = 'Cash';

INSERT INTO expense (sum, category_id, date, time, comment, username, account_id, currency_code) VALUES
    (
        12300,
        (SELECT category_id FROM category WHERE name = 'Presents'),
        '2020-12-15',
        '14:30:53',
        'Christmas presents for whole family',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    ),
    (
        530.50,
        (SELECT category_id FROM category WHERE name = 'Food'),
        '2021-01-05',
        '11:28:00',
        'Vegetables and fruit on local market',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Cash'),
        'UAH'
    ),
    (
        11700,
        (SELECT category_id FROM category WHERE name = 'Apartment Rent'),
        '2021-01-02',
        '12:14:10',
        'Apartment rent',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Cash'),
        'UAH'
    ),
    (
        500,
        (SELECT category_id FROM category WHERE name = 'Clothes'),
        '2021-01-08',
        '11:22:10',
        'New t-shirt',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Cash'),
        'UAH'
    ),
    (
        24856,
        (SELECT category_id FROM category WHERE name = 'Travel'),
        '2021-01-07',
        '19:12:19',
        'Tickets booking',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Cash'),
        'UAH'
    ),
    (
        1100,
        (SELECT category_id FROM category WHERE name = 'Health Care'),
        '2021-01-11',
        '09:47:39',
        'Vaccination against coronavirus',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Cash'),
        'UAH'
    ),
    (
        390,
        (SELECT category_id FROM category WHERE name = 'Mobile and Internet'),
        '2021-01-03',
        '19:47:39',
        'Internet',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Cash'),
        'UAH'
    ),
    (
        298.63,
        (SELECT category_id FROM category WHERE name = 'Education'),
        '2021-01-04',
        '15:03:04',
        'Spring Boot course on Udemy',
        'demo',
        (SELECT account_id FROM account WHERE type = 'Debit Card'),
        'UAH'
    );

UPDATE account SET summary = (summary - 12598.63) WHERE type = 'Debit Card';
UPDATE account SET summary = (summary - 39076.5) WHERE type = 'Cash';